### ISSUE TITLE
Unable to use LE cert

### ISSUE THREAD

**Issue by avidsapp** [dmp1ce/nginx-proxy-letsencrypt#25]
I switched from jwilder/nginx-proxy to use LetsEncrypt. It was working the other night as expected. Today, the domain using LE is referencing another proxied domain's non-LE cert in the browser (NET::ERR_CERT_COMMON_NAME_INVALID). To clarify, I'd like to use both LE and non-LE certs. Logs are as following:

```
letsencrypt.1 | Creating/renewal REMOVED.COM certificates... (REMOVED.COM)
letsencrypt.1 | 2015-12-16 07:03:17,428:ERROR:simp_le:197: Existing (REMOVED.COM, DOMAIN.REMOVED.COM) and requested (REMOVED.COM) SANs mismatch
letsencrypt.1 | Sleep for 3600s

...

letsencrypt.1 | Waiting 10s before updating certs...
letsencrypt.1 | Creating/renewal REMOVED.COM certificates... (REMOVED.COM DOMAIN.REMOVED.COM)
letsencrypt.1 | 2015-12-16 07:04:45,716:INFO:simp_le:1117: Certificates already exist and renewal is not necessary, exiting with status code 1.
letsencrypt.1 | Sleep for 3600s
```

Using docker-compose:

Proxied container docker-compose.yml:

```
...
environment:
    - VIRTUAL_HOST=REMOVED.COM,DOMAIN.REMOVED.COM
    - LETSENCRYPT_HOST=REMOVED.COM,DOMAIN.REMOVED.COM
    - LETSENCRYPT_EMAIL=not@ssociatied.com
...
```

Proxy container docker-compose.yml:

```
proxy:
  build: .
  restart: always
  volumes:
    - /path/to/certs:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - 80:80
    - 443:443
```

Proxy container Dockerfile:

```
FROM dmp1ce/nginx-proxy-letsencrypt

RUN { \
      echo 'server_tokens off;'; \
      echo 'client_max_body_size 100m;'; \
    } > /etc/nginx/conf.d/my_proxy.conf
```
